export const general = [
  "It's just an old game",
  'If you want to cheat go to an easy mode server',
  'Have Fun',
  'Play Together',
  "Previous Rule Doesn't Apply to BST or Noobs",
  'No RMT',
  'No Exploiting Bugs',
  'No MPK',
]

export const ashitaApproved = [
  'Allmaps',
  'Antiemote',
  'Ashitacast',
  'AshitaFishAid',
  'ASCII-Joy',
  'Aspect',
  'Attendance',
  'Barfiller (use at your own risk, known to cause crashes)',
  'Battlemod',
  'Cfhblock',
  'Chains',
  'Chaintimer',
  'Changecall',
  'Chatmon (this addon is only approved in its default script state - any custom modification to addons must be published and approved as separate new addons)',
  'Checker',
  'Claimbar',
  'CleanCS',
  'Clearpartybars',
  'Clock',
  'Config',
  'ConsolidatedUI (also known as "HXUI")',
  'Craftmon',
  'Crossbar',
  'CTimers',
  'CurrentTime',
  'Customhud',
  'Debuffed',
  'Deeps',
  'DigDig',
  'DiscordRPC',
  'Distance',
  'Dont Drop The Soap',
  'Drawdistance',
  'Duration',
  'EnemyBuffs',
  'Enternity',
  'Equipviewer',
  'Equipmon',
  'Expmon',
  'Fadeout',
  'FastCS',
  'Fillmode (this function can be used in Ashita but players are not allowed to initiate actions that would be impossible without using fillmode. Example: If you locate a monster through a wall using fillmode, pulling that monster would be prohibited if the monster would not be able to be pulled without the use of fillmode.)',
  'Filterless',
  'Filters',
  'Find',
  'Findall',
  'Fishaid',
  'FishingInfo',
  'Fps',
  'GBinder',
  'GearFinder',
  'Gearlock',
  'Giltracker',
  'GlamourUI',
  'Hardwaremouse',
  'HGather',
  'Hideconsole',
  'Hideparty',
  'Hush',
  'Ibar',
  'Ime',
  'Imguistyle',
  'Instantah',
  'InstantChat (use at own risk, known to be crash prone)',
  'InvTracker',
  'InventoryCounter',
  'Itemwatch',
  'Kparser',
  'Legacyac',
  'Links',
  'Logs',
  'Logincmd',
  'Logger (part of XITools)',
  'Luashitacast',
  'Macrofix',
  'MacroMaster',
  'Mapdot',
  'Me (part of XITools)',
  'Meteorologist',
  'Minimap',
  'Minimap-helper',
  'Minimapmon',
  'MobDB',
  'Mountmuzzle',
  'Move',
  'Nameplate',
  'Nocombat',
  'Nolock',
  'NoName',
  'Packetflow (known to cause odd issues, use at your own risk)',
  'Packrat',
  'Parse',
  'Partybuffs',
  'Pbar',
  'Petinfo (including the updated PetInfo by Ayechonk)',
  'PlayerInfo',
  'Points',
  'Rcheck',
  'Recast',
  'Scoreboard',
  'Sexchange',
  'Shorthand (using this add-on to claim monsters or using shorthand in a manner that gives a player an unfair advantage is forbidden)',
  'Simplelog',
  'Singlerace',
  'Skillchain',
  'Skillchains',
  'Status',
  'Statustimers',
  'Stfu',
  'Stylist',
  'TargetInfo',
  'Targetlines',
  'tCrossbar',
  'Tgt (part of XITools)',
  'tHotBar',
  'Ticker',
  'Timestamp',
  'Timers',
  'Toon',
  'Tparty',
  'Tracker (part of XITools)',
  'TreasurePool',
  'us (part of XITools)',
  'Watchexp',
  'Xicamera',
  'XivParty',
  'Xipivot',
  'XITools',
  'Xivbar',
  'XIVHotbar',
  'XivHotbar2',
  'Xivui (use at your own risk, known to be crash prone)',
  'Yield',
  'Zoom',
  'ZoneTimer',
]

export const ashitaBanned = [
  'Ahgo',
  'Alertaru',
  'ApRadar',
  'Auctioneer',
  'Autojoin',
  'Autorespond',
  'Bellhop',
  'BoxDestroyer',
  'ButterFeet',
  'Chamcham',
  'CombatMessages',
  'Crafty',
  'Dats(we already package Xipivot with the installer and use it to do our dat swaps - we do not want this to interfere with Xipivot and cause technical issues for players)',
  'Debuff (Cancel is not allowed, so this is not allowed either)',
  'Fastfollow',
  'FFXIFocusTarget',
  'Filterscan',
  'FinalAlert',
  'EnemyCastBar',
  'Gateway',
  'Gmcommand',
  'ja0wait, or any addon that functions similarly (bypassing animation lock for abilities)',
  'LootTable',
  'Lootwhore',
  'Lotomatic',
  'Multisend',
  'No-ckback',
  'Nomad',
  'NpcIt',
  'OnEvent',
  'Packer',
  'Paranormal',
  'PartyPull',
  'Peekaboo',
  'Repeat',
  'Repeater',
  'RFKAway (and related forks)',
  'SendTarget',
  'Servo',
  'Skeletonkey',
  'Synplicity',
  'Trade',
  'Watchdog',
  'Widescantool',
  'Windowerinput',
]

export const windowerApproved = [
  'Allmaps',
  'Attendance',
  'BalloonStoryAddon',
  'Barfiller (use at your own risk, known to cause crashes)',
  'Battlemod',
  'Battlestations',
  'BitsXP',
  'Blist',
  'CellHelp',
  'Chars',
  'ChatLink',
  'Chatmon (this addon is only approved in its default script state - any custom modification to addons must be published and approved as separate new addons)',
  'Clock',
  'Config',
  'ConsoleBG',
  'CTimers',
  'Debuffed',
  'DelayMeNot',
  'Digger',
  'Distance',
  'Distance',
  'DistancePlus',
  'DParty',
  'Dressup',
  'EnemyBar',
  'Enemybarbasic',
  'EnemyList',
  'Enternity',
  'Equipviewer',
  'Expmon',
  'FastCS',
  'Findall',
  'Ffxidb',
  'ffxifeesh',
  'Gametime',
  'GearSwap',
  'Giltracker',
  'Highlight',
  'InfoBar',
  'InstaLS',
  'InvTracker',
  'InventoryCounter',
  'Juggler',
  'Kparser',
  'Linker',
  'Logger',
  'Lookup',
  'MacroChanger',
  'MobLevel',
  'Nostrum',
  'Parse',
  'Partybuffs',
  'PartyHints',
  'PetTP',
  'PluginManager',
  'Pointwatch',
  'Porter',
  'Revisible',
  'ruptchat',
  'Scoreboard',
  'SetBGM',
  'Sh_tlist',
  'Silence',
  'Shortcuts',
  'Shorthand (using this add-on to claim monsters or using shorthand in a manner that gives a player an unfair advantage is forbidden)',
  'Skillchains',
  'SpeedChecker',
  'SpellChecker',
  'Stopwatch',
  'Targetbar',
  'TargetInfo',
  'Tickle',
  'Timers',
  'Timestamp',
  'TParty',
  'Translate',
  'TreasurePool',
  'Update',
  'VisibleFavor',
  'WinControl',
  'Wireframe (this function can be used in Windower but players are not allowed to initiate actions that would be impossible without using wireframe. Example: If you locate a monster through a wall using wireframe, pulling that monster would be prohibited if the monster would not be able to be pulled without the use of wireframe.)',
  'Xicamera',
  'Xivcrossbar',
  'Xivhotbar',
  'XivHotbar2',
  'XivParty',
  'xivpetbar',
  'Xipivot',
  'Zonename',
  'Zonetimer',
]

export const windowerBanned = [
  'AEcho',
  'Anchor',
  'AnnounceTarget',
  'AnsweringMachine',
  'ApRadar',
  'AuctionHelper',
  'AutoControl',
  'Autoenterkey',
  'AutoInvite',
  'AutoJoin',
  'AutoRA',
  'Azi',
  'BoxDestroyer',
  'Cancel',
  'CapeTrader',
  'ChatPorter',
  'CombatMessages',
  'Craft',
  'CurePlease',
  'DynamisHelper',
  'EasyFarm-master',
  'EnemyBar2',
  'EnemyCastBar',
  'Eval',
  'FFXIFocusTarget',
  'FFXItargeter',
  'Fisher',
  'FinalAlert',
  'InfoReplacer',
  'Itemizer',
  'ja0wait, or any addon that functions similarly (bypassing animation lock for abilities)',
  'JobChange',
  'LatentChecker',
  'Maga',
  'MobCompass',
  'Naga',
  'ObiAway',
  'OhShi',
  'Omen',
  'Organizer',
  'Plasmon',
  'Pouches',
  'Quetz',
  'QuickTrade',
  'RAWR',
  'React',
  'Reive',
  'Respond',
  'Rhombus',
  'Roller',
  'SellNPC',
  'Send',
  'Shopper',
  'Smeagol',
  'Sparks',
  'STNA',
  'SubTarget',
  'Superwarp',
  'Temps',
  'Text',
  'THTracker',
  'Trade',
  'TradeNPC',
  'Treasury',
  'UnityNPC',
  'UNM2.0',
  'Voidwatch',
  'VWHL',
  'WarnMe',
  'Yush',
]

export const rules = {
  general,
  ashitaApproved,
  ashitaBanned,
  windowerApproved,
  windowerBanned,
}
